#!/bin/sh

if [ -f 8x8.fon.gz ]; then gunzip -f 8x8.fon.gz; fi
if [ -f 8x8.fon ]; then mv 8x8.fon 8x8.fon.save; fi

find -name '*.spr' -o -name '*.spr.gz' -o -name '*.fon' -o -name '*.fon.gz' -o -name '*.pal' | xargs -r rm

if [ -f 8x8.fon.save ]; then mv 8x8.fon.save 8x8.fon; fi
if [ -f 8x8.fon ]; then gzip -9 -f 8x8.fon; fi
